#!/usr/bin/env python3
"""Generate ``config/aoi.json`` — the one authoritative definition of the AOI.

Every other script and every clip/extract operation reads its extent from that
file, so the 10 x 10 mile box is defined in exactly one place.

    python3 scripts/make_aoi.py
"""

from __future__ import annotations

import json
import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from geoutil import METERS_PER_MILE, dd_to_dm, ll_to_utm, utm_to_ll  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "config" / "aoi.json"

# 23740 Storm Mountain Rd, Rapid City, SD 57702 (Storm Mountain Training Grounds).
CENTER_LAT = 43.964
CENTER_LON = -103.377
BOX_MILES = 10.0
UTM_ZONE = 13


def build() -> dict:
    half_m = (BOX_MILES / 2.0) * METERS_PER_MILE
    cx, cy = ll_to_utm(CENTER_LAT, CENTER_LON, UTM_ZONE)
    xmin, ymin, xmax, ymax = cx - half_m, cy - half_m, cx + half_m, cy + half_m

    corners = {
        "sw": utm_to_ll(xmin, ymin, UTM_ZONE),
        "se": utm_to_ll(xmax, ymin, UTM_ZONE),
        "nw": utm_to_ll(xmin, ymax, UTM_ZONE),
        "ne": utm_to_ll(xmax, ymax, UTM_ZONE),
    }
    lats = [lat for lat, _ in corners.values()]
    lons = [lon for _, lon in corners.values()]
    # Geographic envelope of the projected square. The square's edges bow in
    # lat/long, so this envelope is very slightly larger than the square itself.
    # Clip with it and you are guaranteed full coverage.
    geo = {
        "ymin": min(lats),
        "ymax": max(lats),
        "xmin": min(lons),
        "xmax": max(lons),
    }

    return {
        "_comment": "Generated by scripts/make_aoi.py — do not hand-edit.",
        "name": "Storm Mountain Training Grounds AOI",
        "center": {
            "address": "23740 Storm Mountain Rd, Rapid City, SD 57702",
            "lat": CENTER_LAT,
            "lon": CENTER_LON,
            "utm_easting_m": round(cx, 2),
            "utm_northing_m": round(cy, 2),
        },
        "box_miles": BOX_MILES,
        "administrative": {
            "forest": "Black Hills National Forest",
            "county": "Pennington County, South Dakota",
            "nearest_communities": ["Rockerville", "Rapid City", "Hill City", "Keystone"],
        },
        "crs": {
            "projected": {
                "epsg": 26913,
                "name": "NAD 1983 UTM Zone 13N",
                "units": "meters",
                "use_for": "map view, all analysis, all layouts",
            },
            "geographic": {
                "epsg": 4269,
                "name": "NAD 1983",
                "use_for": "graticule, coordinate tables, datum statement",
            },
            "datum_statement": "North American 1983 Datum. Lat/Long Grid",
        },
        "extent_utm_26913": {
            "xmin": round(xmin, 2),
            "ymin": round(ymin, 2),
            "xmax": round(xmax, 2),
            "ymax": round(ymax, 2),
            "width_m": round(xmax - xmin, 2),
            "height_m": round(ymax - ymin, 2),
        },
        "extent_geographic_4269": {k: round(v, 6) for k, v in geo.items()},
        "extent_geographic_dm": {
            "north": dd_to_dm(geo["ymax"], True),
            "south": dd_to_dm(geo["ymin"], True),
            "west": dd_to_dm(geo["xmin"], False),
            "east": dd_to_dm(geo["xmax"], False),
        },
        "bbox_wgs84_order": [
            round(geo["xmin"], 6),
            round(geo["ymin"], 6),
            round(geo["xmax"], 6),
            round(geo["ymax"], 6),
        ],
        "download_buffer_miles": 2.0,
        "download_note": (
            "Pull base data to the AOI plus the 2 mile buffer. Layouts pan and the "
            "briefing map zooms out; clipping tight to the box guarantees white "
            "corners on the first product you build."
        ),
        "hillshade_parameters": {"azimuth": 315, "altitude": 45, "z_factor": 1},
        "contour_interval_ft": {"intermediate": 40, "index": 200},
    }


def main() -> int:
    aoi = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(aoi, indent=2) + "\n")

    e = aoi["extent_utm_26913"]
    g = aoi["extent_geographic_dm"]
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  UTM 13N   : {e['xmin']:.1f}, {e['ymin']:.1f}  ->  {e['xmax']:.1f}, {e['ymax']:.1f}")
    print(f"  geographic: {g['north']} / {g['south']} / {g['west']} / {g['east']}")
    diag = math.hypot(e["width_m"], e["height_m"]) / METERS_PER_MILE
    print(f"  box {aoi['box_miles']:.0f} x {aoi['box_miles']:.0f} mi, diagonal {diag:.2f} mi")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
